# Generated by Django 4.2.4 on 2023-08-10 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=650),
            preserve_default=False,
        ),
    ]
